### ISSUE TITLE
Homeassistant Token

### ISSUE THREAD

**Issue by dutchronnie** [marq24/emacberry.com#31]
When i enter a homeassistant token, i get a Fatal GPSlogger II error.
I have the error page sent by the app.

**Comment by marq24** [comment]
... just received it by mail...

**Comment by marq24** [comment]
looks like that you did not specify a valid URL - how your HA instance could be reached - are you sure that it started with `http://` or `https://` ?!

**Comment by dutchronnie** [comment]
Stupid of me, i have copied the url, and past it in the app. but i didn't see that HTTPS wasn't there.
Now i managed to put in the token.
But i don't see an entity in home assistant with the location.

I am planning to use an old phone with GPSLOGGER II as a tracking device for my car. I jope i can manage that😊

**Comment by marq24** [comment]
have you enabled "permanent transfer" in the GPSLogger HA-Settings ? In any other case you must start logging...

**Comment by dutchronnie** [comment]
Yes, it is enabled.

**Comment by dutchronnie** [comment]
Is there a name for the entitie in homeassistant?

**Comment by marq24** [comment]
`device_tracker.gpslogger_ii_tracker`

**Comment by dutchronnie** [comment]
Strange, i don't see this entity in homeassistant. I also don't get any errors.
Are the positions also sent when the phone is only connected by wifi?
For now, i don't have a simcard in the phone.

When i do the filesharing with the email, the position is sent.

**Comment by marq24** [comment]
there will be no error log, when the specified request/URL is not reachable... I guess that's your current problem... You must ensure, that the URL is reachable from the public internet... And also copy & pase the long term access token might be a bit tricky... 

What you can try is to start logging, and check, if then (depending on your selected update interval) the app will send your current position (IF a position is available at all) to your HA instance...

**Comment by dutchronnie** [comment]
The url is reachable, it's a adress in duckdns, which i can access from the internet.

This is the format: https://name.duckdns.org:8123

Then i add the token, and get the message "homeassistant failed to connect"

**Comment by marq24** [comment]
are you sure that you must use the port, when accessing HA from the public internet?

**Comment by dutchronnie** [comment]
Yes, i have tried without port, but that doesn't work

**Comment by dutchronnie** [comment]
Now it works.
I picked up another phone, did exactly the sam and with this phone i have a connection with homeassistant.
I think something wrong with the other phone.

Thanks, i do some experiments if i can use this phone as a tracker for my car.
